
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import com.mysql.cj.protocol.Resultset;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;

import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class FAdmin extends javax.swing.JFrame {
    int economy,business,first,harga,beli,total,bayar,kembali;
    private Object jOptionPane;
    private Statement St;
    private Connection Con;
    
    private String sql="";
    
    
    public FAdmin() {
        initComponents();
        load_data();
        IDOtomatis();
    }
    
    public void load_data(){
        java.sql.Connection kon=koneksi.koneksiDb();
        Object header[]={"Nama Pembeli","Jumlah Beli","Total Bayar","Pembayaran","Kembalian"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        jTable1.setModel(data);
        String sql_data="SELECT * FROM penjualan";
        
        try
        {
            java.sql.Statement st=kon.createStatement();
            java.sql.ResultSet rs=st.executeQuery(sql_data);
            while(rs.next())
            {
                String d1=rs.getString(1);
                String d2=rs.getString(2);
                String d3=rs.getString(3);
                String d4=rs.getString(4);
                String d5=rs.getString(5);
                
                String d[]={d1,d2,d3,d4,d5};
                data.addRow(d);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    
     public void IDOtomatis(){      
        try
        {
            java.sql.Connection kon=koneksi.koneksiDb();
            java.sql.Statement st=kon.createStatement();
            String sql_id="SELECT * FROM penjualan ORDER BY nama_pembeli";
            java.sql.ResultSet rs=st.executeQuery(sql_id);
            
            while (rs.next()) {
            String d1 = rs.getString("nama_pembeli");
            String d[] = { d1 };
            data.addRow(d);
            }
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cb_hari = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rb_economy = new javax.swing.JRadioButton();
        rb_business = new javax.swing.JRadioButton();
        rb_first = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tf_harga = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_jumlah = new javax.swing.JTextField();
        tf_total = new javax.swing.JTextField();
        tf_bayar = new javax.swing.JTextField();
        tf_kembalian = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_input = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Schadow BT", 1, 18)); // NOI18N
        jLabel1.setText("Penjualan Tiket Pesawat");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));

        jLabel2.setText("Tujuan");

        cb_hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kota", "Jakarta", "Bandung", "Banjarmasin", "Papua" }));
        cb_hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hariActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Tiket");

        rb_economy.setText("Economy Class");
        rb_economy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_economyActionPerformed(evt);
            }
        });

        rb_business.setText("Business Class");
        rb_business.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_businessActionPerformed(evt);
            }
        });

        rb_first.setText("First Class");
        rb_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_firstActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Pemesanan"));

        jLabel5.setText("Nama Pembeli");

        jLabel6.setText("Jumlah Beli");

        jLabel7.setText("Total Bayar");

        jLabel8.setText("Pembayaran");

        jLabel9.setText("Kembalian");

        tf_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_jumlahActionPerformed(evt);
            }
        });
        tf_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_jumlahKeyReleased(evt);
            }
        });

        tf_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bayarActionPerformed(evt);
            }
        });
        tf_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_bayarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nama)
                    .addComponent(tf_jumlah)
                    .addComponent(tf_total)
                    .addComponent(tf_bayar)
                    .addComponent(tf_kembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_first)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rb_economy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_business))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rb_economy)
                    .addComponent(rb_business))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_first)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 330));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        btn_input.setText("Clear");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        btn_cetak.setText("SIMPAN");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Pembeli", "Jumlah Beli", "Total Bayar", "Pembayaran", "Kembalian"
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Nama Pembeli");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Jumlah Beli");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Total Bayar");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Pembayaran");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Kembalian");
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_input)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_keluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_input)
                    .addComponent(btn_keluar)
                    .addComponent(btn_cetak)
                    .addComponent(btn_edit)
                    .addComponent(btn_hapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 480, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hariActionPerformed
        // TODO add your handling code here:
        //digunakan untuk menentukan harga setiap hari
        if(cb_hari.getSelectedItem().equals("Pilih Hari"))
        {
            buttonGroup1.clearSelection();
            tf_harga.setText("");
        }
                else if(cb_hari.getSelectedItem().equals("Jakarta"))
        {
            economy=50000;
            business=70000;
            first=90000;
        }
                else if(cb_hari.getSelectedItem().equals("Bandung"))
        {
            economy=56000;
            business=76000;
            first=96000;
        }
                else if(cb_hari.getSelectedItem().equals("Banjarmasin"))
        {
            economy=57000;
            business=77000;
            first=97000;
        }
                else if(cb_hari.getSelectedItem().equals("Papua"))
        {
            economy=58000;
            business=78000;
            first=98000;
        }

    }//GEN-LAST:event_cb_hariActionPerformed

    private void rb_economyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_economyActionPerformed
        // TODO add your handling code here:
        if(rb_economy.isSelected())
        {
            tf_harga.setText(String.valueOf(economy));
        }
    }//GEN-LAST:event_rb_economyActionPerformed

    private void rb_businessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_businessActionPerformed
        // TODO add your handling code here:
        if(rb_business.isSelected())
        {
            tf_harga.setText(String.valueOf(business));
        }
    }//GEN-LAST:event_rb_businessActionPerformed

    private void rb_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_firstActionPerformed
        // TODO add your handling code here:
        if(rb_first.isSelected())
        {
            tf_harga.setText(String.valueOf(first));
        }
    }//GEN-LAST:event_rb_firstActionPerformed

    private void tf_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_jumlahActionPerformed
        // TODO add your handling code here:
        beli=Integer.parseInt(tf_jumlah.getText());
        harga=Integer.parseInt(tf_harga.getText());
        total=bayar*harga;
        tf_total.setText(String.valueOf(total));
    }//GEN-LAST:event_tf_jumlahActionPerformed

    private void tf_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bayarActionPerformed
        // TODO add your handling code here:
        bayar=Integer.parseInt(tf_bayar.getText());
        kembali=Integer.parseInt(tf_total.getText());
        total=bayar-kembali;
        tf_kembalian.setText(String.valueOf(total));
    }//GEN-LAST:event_tf_bayarActionPerformed

    private void tf_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jumlahKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(tf_harga.getText());
        b=Integer.valueOf(tf_jumlah.getText());
        c=a*b;
        tf_total.setText(""+c);
    }//GEN-LAST:event_tf_jumlahKeyReleased

    private void tf_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_bayarKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(tf_bayar.getText());
        b=Integer.valueOf(tf_total.getText());
        c=a-b;
        tf_kembalian.setText(""+c);
    }//GEN-LAST:event_tf_bayarKeyReleased

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        tf_harga.setText("");
        cb_hari.setSelectedItem("Pilih Jadwal Hari");
        tf_nama.setText("");
        tf_total.setText("");
        tf_jumlah.setText("");
        tf_bayar.setText("");
        tf_kembalian.setText("");
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
    int answer = JOptionPane.showConfirmDialog(null, "Anda akan keluar", "Keluar", JOptionPane.OK_OPTION);
    if (answer == JOptionPane.OK_OPTION) {
        System.exit(0);
    }

    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        btn_cetak.setText((String)cb_hari.getSelectedItem());
     try {
        // Get data from text fields
        String nama = tf_nama.getText();
        String jumlah = tf_jumlah.getText();
        String totalBayar = tf_total.getText();
        String pembayaran = tf_bayar.getText();
        String kembalian = tf_kembalian.getText();

        // Connect to the database using your custom class
        java.sql.Connection kon=koneksi.koneksiDb();

        // Prepare the SQL statement to insert data into the database
        String insertQuery = "INSERT INTO penjualan (nama_pembeli, jumlah_beli, total_bayar, pembayaran, kembalian) VALUES (?, ?, ?, ?, ?)";
        
        try (var pst = kon.prepareStatement(insertQuery)) {
            pst.setString(1, nama);
            pst.setString(2, jumlah);
            pst.setString(3, totalBayar);
            pst.setString(4, pembayaran);
            pst.setString(5, kembalian);

            // Execute the insert statement
            int rowsAffected = pst.executeUpdate();

            // Check if the insert operation was successful
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke database.");

                // Add a new row to the table
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{nama, jumlah, totalBayar, pembayaran, kembalian});

                // Clear the text fields
                tf_nama.setText("");
                tf_jumlah.setText("");
                tf_total.setText("");
                tf_bayar.setText("");
                tf_kembalian.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke database.");
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "SQL error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
try {
    // Get the selected row index
    int selectedRow = jTable1.getSelectedRow();

    // Check if a row is selected
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        return;
    }

    // Get the value from the 'nama_pembeli' column
    Object selectedIdObject = jTable1.getValueAt(selectedRow, 0);

    // Check if the selected 'nama_pembeli' is not null
    if (selectedIdObject != null) {
        // Convert the value to String (assuming 'nama_pembeli' is of type String)
        String selectedNamaPembeli = selectedIdObject.toString();

        // Connect to the database using your custom class
        java.sql.Connection kon = koneksi.koneksiDb();

        // Prepare the SQL statement to delete the record
        try (var pst = kon.prepareStatement("DELETE FROM penjualan WHERE nama_pembeli = ?")) {
            pst.setString(1, selectedNamaPembeli);

            // Execute the delete statement
            int rowsAffected = pst.executeUpdate();

            // Check if the delete operation was successful
            if (rowsAffected > 0) {
                // Remove the selected row from the table model
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.removeRow(selectedRow);

                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the record.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQL error: " + ex.getMessage());
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage());
}
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed

    int selectedRow = jTable1.getSelectedRow();

// Check if a row is selected
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a row to edit.");
    return;
}

// Get the values from the selected row
Object namaObject = jTable1.getValueAt(selectedRow, 0);
Object jumlahObject = jTable1.getValueAt(selectedRow, 1);
Object totalBayarObject = jTable1.getValueAt(selectedRow, 2);
Object pembayaranObject = jTable1.getValueAt(selectedRow, 3);
Object kembalianObject = jTable1.getValueAt(selectedRow, 4);

// Assuming your ID column is of type Integer
// Adjust the data types according to your table structure
String nama = (String) namaObject;
int jumlah = Integer.parseInt(jumlahObject.toString());
int totalBayar = Integer.parseInt(totalBayarObject.toString());
int pembayaran = Integer.parseInt(pembayaranObject.toString());
int kembalian = Integer.parseInt(kembalianObject.toString());

// Prompt the user to edit the values
String editedNama = JOptionPane.showInputDialog(this, "Edit Nama Pembeli", nama);
int editedJumlah = getValidIntInput("Edit Jumlah Beli", jumlah);
int editedTotalBayar = getValidIntInput("Edit Total Bayar", totalBayar);
int editedPembayaran = getValidIntInput("Edit Pembayaran", pembayaran);
int editedKembalian = getValidIntInput("Edit Kembalian", kembalian);

try {
    // Connect to the database using try-with-resources
    try (java.sql.Connection kon = koneksi.koneksiDb();
         // Prepare the SQL statement to update the record
         var pst = kon.prepareStatement("UPDATE penjualan SET nama_pembeli=?, jumlah_beli=?, total_bayar=?, pembayaran=?, kembalian=?")) {

        pst.setString(1, editedNama);
        pst.setInt(2, editedJumlah);
        pst.setInt(3, editedTotalBayar);
        pst.setInt(4, editedPembayaran);
        pst.setInt(5, editedKembalian);
//        pst.setInt(6, selectedRow + 1); // Adjust this line based on your table structure

        // Execute the update statement
        int rowsAffected = pst.executeUpdate();

        // Check if the update operation was successful
        if (rowsAffected > 0) {
            // Update the values in the table model
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setValueAt(editedNama, selectedRow, 0);
            model.setValueAt(editedJumlah, selectedRow, 1);
            model.setValueAt(editedTotalBayar, selectedRow, 2);
            model.setValueAt(editedPembayaran, selectedRow, 3);
            model.setValueAt(editedKembalian, selectedRow, 4);

            JOptionPane.showMessageDialog(this, "Record updated successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update the record.");
        }
    }
} catch (SQLException ex) {
    ex.printStackTrace(); // Cetak trace eksepsi untuk pemecahan masalah
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
}
    }//GEN-LAST:event_btn_editActionPerformed

    
    private int getValidIntInput(String message, int defaultValue) {
    while (true) {
        try {
            String input = JOptionPane.showInputDialog(this, message, defaultValue);
            if (input == null) {
                // Jika pengguna membatalkan input dialog, kembalikan nilai default
                return defaultValue;
            }
            return Integer.parseInt(input);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid number.");
        }
    }
}
    
    private static void addRow(DefaultTableModel model, String[] data) {
    model.addRow(data);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_keluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_hari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rb_business;
    private javax.swing.JRadioButton rb_economy;
    private javax.swing.JRadioButton rb_first;
    private javax.swing.JTextField tf_bayar;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_jumlah;
    private javax.swing.JTextField tf_kembalian;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_total;
    // End of variables declaration//GEN-END:variables

    private static class data {

        private static void addRow(String[] d) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public data() {
        }
    }

}
